PROJECTS="$HOME/projects"

# For passwords and such...
[ -s $HOME/.env ] && . $HOME/.env

# Add Python installed bins to path
[ -d $HOME/.local/bin ] && export PATH+=:"$HOME/.local/bin"

# Our own bins
[ -d $HOME/dotfiles/bin ] && export PATH+=:"$HOME/projects/dotfiles/bin"

# For switching accounts...
[ -d "$HOME/projects/change_adsl" ] && export PATH+=:"$HOME/projects/change_adsl"

# Java
[ -d /usr/lib/jvm/java-7-openjdk-amd64/ ] && export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/; export PATH+=:"$JAVA_HOME/bin"

# NVM ----------------------------------------------------
[ -d "$HOME/.nvm" ] && export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# added by travis gem
[ -f "$HOME/.travis/travis.sh" ] && source "$HOME/.travis/travis.sh"

# Sauce Credentials -------------------------------------
# export SAUCE_USERNAME="ponelat"
# export SAUCE_ACCESS_KEY="KEYKEYKEY"

# Source the 'rvm' function
# Add RVM to PATH for scripting 
[ -s "$HOME/.rvm/scripts/rvm" ] && . "$HOME/.rvm/scripts/rvm"; export PATH="$PATH:$HOME/.rvm/bin"

# Linuxbrew, see:
echo $HOME/.linuxbrew
if [ -d "$HOME/.linuxbrew" ]; then
  export PATH="$HOME/.linuxbrew/bin:$PATH"
  export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"

  [ -f "`brew --prefix`/etc/bash_completion" ] && . "`brew --prefix`/etc/bash_completion"

  # Linux brew bash completions
  if [ -d "$(brew --prefix)/etc/profile.d" ] ; then
    for com in `\ls $(brew --prefix)/etc/profile.d/*`; do
      . $com
    done
  fi

  # Linuxbrew sourced files...
  # if [ -d "$(brew --prefix)/etc/bash_completion.d/" ] ; then
  #   for com in `\ls $(brew --prefix)/etc/bash_completion.d/*`; do
  #     echo $com
  #     . $com
  #     done
  # fi

  # Linuxbrew manually sourced files...
  [ -f "$(brew --prefix)/share/liquidprompt" ] && . "$(brew --prefix)/share/liquidprompt" 

fi

# Pick the right editor
[ -n "`type -P vi`" ] && export EDITOR=nvim
[ -n "`type -P vim`" ] && export EDITOR=nvim
[ -n "`type -P nvim`" ] && export EDITOR=nvim

# Add this path for karma (I think)
[ -n "`type -P phantomjs`" ] && export PHANTOMJS_BIN="`type -p phantomjs`"

# Gulp task autocompletion, needs to be after nvm setup
[ -n "`type -P gulp`" ] && eval "$(gulp --completion=bash)"

# Grunt task autocompletion, needs to be after nvm setup
[ -n "`type -P grunt `" ] && eval "$(grunt --completion=bash)"

# Our own completions
if [ -d $HOME/dotfiles/bash_completion.d  ]; then
  for compl in `\ls $HOME/dotfiles/bash_completion.d/*` ; do
    . $compl
  done
fi

# Setup color support
# export TERM=xterm-256color
case "$TERM" in
       xterm*) TERM=xterm-256color
esac

# Base16 Shell
[ -d "$HOME/.config/base16-shell" ] && . "/home/josh/.config/base16-shell/base16-paraiso.dark.sh"

# Correct base16 colors for ls output
[ -x `type -P dircolors` ] && eval `dircolors`

# git  helpers aliases and functions
[ -d "$HOME/.githelpers" ] && . $HOME/.githelpers

# Powerline
# powerline-daemon -q # this should be hiding in $HOME/.local/bin
# POWERLINE_BASH_CONTINUATION=1
# POWERLINE_BASH_SELECT=1
# source "$HOME/.local/lib/python2.7/site-packages/powerline/bindings/shell/powerline.sh"

## Aliases
alias ls='ls -A --color=always --group-directories-first -1 -v'
alias o='xdg-open'
alias n='nvim'
alias .b=". $HOME/.bashrc"
alias .x="$HOME/.xsession"
alias .color="(cd "$HOME/.config/base16-shell/" && . ./colortest)"
alias vib="vi $HOME/.bashrc"
alias nib="nvim $HOME/.bashrc"
alias dotinstall=". $HOME/dotfiles/install.sh"
alias specs="ln -s $PROJECTS/swagger-notes/specs dist/s"
alias impose="ln -fi ../swagger-notes/ui-gulpfile.js gulpfile.js"
alias ne='PATH=$(npm bin):$PATH'
alias damn_gitatt="echo '**/* binary' > .gitattributes && git add .gitattributes && git reset .gitattributes && git checkout .gitattributes"
alias gl="git l -10"

alias drm="docker rm -v $(docker ps -a -q -f status=exited)"
alias drmi="docker rmi $(docker images -f "dangling=true" -q)"

[ ! -z `type -P hub` ] && alias git=hub

# Set vi mode by default
set -o vi
# set show-mode-in-prompt on

###
############### FUNCTIONS
###

## Local variables
# global -maxdepth for 'find'
FIND_MAX_DEPTH=5

# The following function has been moved into it's own file...
# Reboot into windows...
# function windows() {
#   # For this to work without requiring a password, run this...
#   # sudo visudo
#   # then add this to the bottom of sudoers
#   # josh    ALL=(ALL) NOPASSWD: /sbin/shutdown, /sbin/reboot, /sbin/poweroff, /usr/sbin/grub-reboot
#   sudo grub-reboot 4 && sudo reboot
# }

function ns() {
  local FILE=`find_file_ignore_git $1 | s`
  nvim $FILE
}

function nms() {
  local FILE=`find_file_ignore_git $1 | s`
  nvim $FILE
}


function cats() {
  local FILE=`find_file_ignore_git $1 | s`
  echo `cat $FILE | s`
}

function entrs() {
  DIR=$(find . -type d | s)
  ls "$DIR"/* | entr "$*"
}

function be () {
  bundle exec "$*"
}

function lsla() {
  ls -p -cltr "$*" | grep -v /
}

# Some powerful fuzzyfinder shortcuts to help me move around
function s () {
  # see https://github.com/garybernhardt/selecta
  selecta
}

function ss() {
  cd $(find $HOME/projects -maxdepth 2 -type d | s)
}

function lss() {
  args=${1:-.}
  ls `find $args -maxdepth $FIND_MAX_DEPTH | s `
}

function movies() {
  args="/mnt/Data/Movies $HOME/Downloads"
  # xdg-open `find $args -maxdepth $FIND_MAX_DEPTH | s `

  TYPES_STR=avi
  TYPES="m4v mkv mp4"
  for T in $TYPES; do
    TYPES_STR=$TYPES_STR$T'\|'
  done

  xdg-open "`find $args -maxdepth $FIND_MAX_DEPTH -iregex '.*\.\('$TYPES_STR'\)' | s `"
}

function os() {
  args=${1:-.}
  xdg-open `find "$args" -maxdepth $FIND_MAX_DEPTH | s `
}

function cds() {
  # here we have a default value for our arg, go bash!
  # note: the hyphen is part of the syntax ....${var:-default}
  base=${1:-.}
  echo Limited to $FIND_MAX_DEPTH
  cd $(find_dir_ignore_common "$base" -maxdepth $FIND_MAX_DEPTH -type d | s)
}

function cdd() {
  cd `print_parent_paths | s`
}

function count_parent_folders() {
 all=`tr '/' '\n' | wc -l `
 echo $[$all-1]
}

function print_parent_paths() {
  p=`pwd`
  PARENTS=`echo $p | count_parent_folders`
  COUNTER=0
  NUM=2

  while [[ $COUNTER -lt $PARENTS ]]; do
    echo `expr $p : '\(\([^/]*/\)\{'$[$PARENTS-$COUNTER]'\}\)'`
    COUNTER=$[$COUNTER+1]
  done

# expr /hello/bob/and/mary : '\(\([^/]*/\)\{4\}\)'
}

function cpsa() {
  cps --all-folders "$*"
}

function cps() {
  limit=$FIND_MAX_DEPTH
  find_dir_command='find_dir_ignore_common'
  if [ "$1" = "--all-folders" ]; then
    find_dir_command='find_dir'
    shift
  fi
  src_base=${1:-.}
  dest_base=${2:-.}



  src_base_final="$($find_dir_command "$src_base" | s)"
  src=$(find $src_base_final -maxdepth $limit | s)
  dest=$($find_dir_command "$dest_base" | s)

  cp "$src" "$dest"
}

function cpss() {
  src_base=${1:-$HOME/projects}
  dest_base=${2:-.}
  cps "$src_base" "$dest_base"
}

function find_dir_ignore_common() {
  base=${1:-.}
  find $1 -type d \( ! -path "*node_modules*" ! -path '*bower_components*' ! -path '*git*' ! -path '*cache*' \)
}

function find_file_ignore_git() {
  base=${1:-.}
  find $base -type f \( ! -path '*git*' ! -path '*cache*' \)
}

function find_dir() {
  base=${1:-.}
  find "$1" -type d
}

# Run git status if in git repo, else ls -la
# see: https://gist.github.com/andrewberls/6119868#file-cs-sh
function cs {
  clear
  if ! git ls-files >& /dev/null
  then
    ls -a $1
  else
    git status $1
  fi
}


###############################################################################
############ Github gits for ssh-agent
###############################################################################
# See: https://help.github.com/articles/working-with-ssh-key-passphrases#auto-launching-ssh-agent-on-msysgit
###############################################################################
# Note: $HOME/.ssh/environment should not be used, as it
#       already has a different purpose in SSH.

env=$HOME/.ssh/agent.env

# Note: Don't bother checking SSH_AGENT_PID. It's not used
#       by SSH itself, and it might even be incorrect
#       (for example, when using agent-forwarding over SSH).

agent_is_running() {
    if [ "$SSH_AUTH_SOCK" ]; then
        # ssh-add returns:
        #   0 = agent running, has keys
        #   1 = agent running, no keys
        #   2 = agent not running
        ssh-add -l >/dev/null 2>&1 || [ $? -eq 1 ]
    else
        false
    fi
}

agent_has_keys() {
    ssh-add -l >/dev/null 2>&1
}

agent_load_env() {
    . "$env" >/dev/null
}

agent_start() {
    (umask 077; ssh-agent >"$env")
    . "$env" >/dev/null
}

if ! agent_is_running; then
    agent_load_env
fi

# if your keys are not stored in $HOME/.ssh/id_rsa.pub or $HOME/.ssh/id_dsa.pub, you'll need
# to paste the proper path after ssh-add
if ! agent_is_running; then
    agent_start
    ssh-add
elif ! agent_has_keys; then
    ssh-add
fi

unset env


# Prompt
get_root_git_dir() {
    printf "%s" $(pwd | sed "s:$HOME:~:")
}

get_dir() {
    printf "%s" $(pwd | sed "s:$HOME:~:")
}

get_sha() {
    git rev-parse --short HEAD 2>/dev/null
}

# added by travis gem
[ -f /home/josh/.travis/travis.sh ] && source /home/josh/.travis/travis.sh
