# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set my terminal if I'm not in tmux.
# [[ "$TMUX" == "" ]] && TERM=xterm-256color

ZSH_THEME="avit"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="false"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=~/projects/dotfiles/zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(fasd npm docker unaliases)

### Silly people, setting aliases...
# Set by fasd ( set by the ori install, not the zsh-plugin )

### Path
[[ -d "$HOME/.linuxbrew" ]] && PATH="$PATH:$HOME/.linuxbrew/bin"
[[ -d "$HOME/projects/dotfiles/bin" ]] && PATH="$PATH:$HOME/projects/dotfiles/bin"

# project-bins will export a list of dirs, which we'll add to the path
projectBins=`$HOME/projects/dotfiles/bin/project-bins.sh | tr '\n' ':' | sed 's/:$//'`
[ ! -z "$projectBins" ] && PATH="$PATH:$projectBins"

export PATH=$PATH

# Preferred editor for local and remote sessions
# export EDITOR="emacsclient -t"
# export ALTERNATE_EDITOR=""
# export VISUAL="emacsclient -c -a emacs"
export EDITOR="nvim"
export ALTERNATE_EDITOR=""
export VISUAL="nvim"

source $ZSH/oh-my-zsh.sh
export RPROMPT=

# You may need to manually set your language environment
# export LANG=en_UK.UTF-8

bindkey -v

setopt autolist       # Display completion candidates immediately.
setopt cdablevars     # When an argument should be a dir but is not one,
                      # expand it as if it started with ~ (see below).
setopt autonamedirs   # Any parameter that is set to an abosolute directory
                      # name automatically becomes a name for that directory
                      # in the form ~param.
setopt histignoredups # Do not record a command in the history if it is a
                      # duplicate of the previous one.
setopt listtypes      # When listing files that are possible completions,
                      # indicate their types with a trailing character.
setopt nolistbeep     # No bell on ambiguous completion!!


# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/dsa_id"


export RBENV_ROOT=~/.linuxbrew/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

## Need to source...

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

export NVM_DIR="$HOME/.nvm"
[[ -d "$NVM_DIR" ]] || mkdir -p "$NVM_DIR"
[[ -f "$(brew --prefix nvm)/nvm.sh" ]] && . "$(brew --prefix nvm)/nvm.sh"


### Custom imports
### User credentials (dont check this into your repo)
. ~/.env
. ~/projects/dotfiles/funcs/aliases

### Functions 
function zenv() {
  env | fzf | cut -f2 -d=
}
