# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Handles a lot of $PATH stuff, check there first
. ~/.profile

# Set my terminal if I'm not in tmux.
# [[ "$TMUX" == "" ]] && TERM=xterm-256color

ZSH_THEME="avit"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="false"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=~/projects/dotfiles/zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(fasd npm docker unaliases zsh-autosuggestions jira vi-mode-copy-paste aws curl kubectl mvn openssl)

# Preferred editor for local and remote sessions
export EDITOR="emacsclient -c"
export VISUAL="emacsclient -c"
# export ALTERNATE_EDITOR=""
# export VISUAL="emacsclient -c -a emacs"
# export EDITOR="vim"
export ALTERNATE_EDITOR="vim"
# export VISUAL="vim"

source $ZSH/oh-my-zsh.sh
export RPROMPT=

# You may need to manually set your language environment
# export LANG=en_UK.UTF-8

bindkey -v

bindkey '^ ' autosuggest-accept
bindkey "^K" history-beginning-search-backward
bindkey "^J" history-beginning-search-forward

setopt autolist       # Display completion candidates immediately.
setopt cdablevars     # When an argument should be a dir but is not one,
                      # expand it as if it started with ~ (see below).
setopt autonamedirs   # Any parameter that is set to an abosolute directory
                      # name automatically becomes a name for that directory
                      # in the form ~param.
setopt histignoredups # Do not record a command in the history if it is a
                      # duplicate of the previous one.
setopt listtypes      # When listing files that are possible completions,
                      # indicate their types with a trailing character.
setopt nolistbeep     # No bell on ambiguous completion!!


# Compilation flags
# export ARCHFLAGS="-arch x86_64"

### Custom imports
### User credentials (dont check this into your repo)
. ~/projects/dotfiles/funcs/aliases
. ~/projects/dotfiles/funcs/funcs

## Ruby
# export RBENV_ROOT="$HOME/.linuxbrew/var/rbenv"
# rbenv >/dev/null 2>&1 && eval "`rbenv init -`"

### Yarn
# if which yarn > /dev/null; then
  # PATH="$PATH:`yarn global bin`"
# fi

### Base 16
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

### FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# fbr - checkout git branch (including remote branches), sorted by most recent commit, limit 30 last branches
fbr() {
  local branches branch
  branches=$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format="%(refname:short)") &&
  branch=$(echo "$branches" |
           fzf-tmux -d $(( 2 + $(wc -l <<< "$branches") )) +m) &&
  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

# fco - checkout git branch/tag
fco() {
  local tags branches target
  tags=$(
    git tag | awk '{print "\x1b[31;1mtag\x1b[m\t" $1}') || return
  branches=$(
    git branch --all | grep -v HEAD             |
    sed "s/.* //"    | sed "s#remotes/[^/]*/##" |
    sort -u          | awk '{print "\x1b[34;1mbranch\x1b[m\t" $1}') || return
  target=$(
    (echo "$tags"; echo "$branches") |
    fzf-tmux -l30 -- --no-hscroll --ansi +m -d "\t" -n 2) || return
  git checkout $(echo "$target" | awk '{print $2}')
}


# export PATH="$HOME/apps/julia/bin:$PATH"
# [[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn

if [ -f $HOME/.nix-profile/etc/profile.d/nix.sh ] ; then
  # Need to add this for _other_ programs to identify it, as nix.sh doesn't work for emacs
  source $HOME/.nix-profile/etc/profile.d/nix.sh
  export NIX_PATH="nixpkgs=$HOME/.nix-defexpr/channels/nixos-18.03"
fi

alias ddive="docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $(which docker):/bin/docker \
    wagoodman/dive:latest"


fpath=($HOME/.zsh-completion/ $fpath )

# kitty
autoload -Uz compinit
compinit
# # Completion for kitty
# kitty + complete setup zsh | source /dev/stdin

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/josh/.sdkman"
[[ -s "/home/josh/.sdkman/bin/sdkman-init.sh" ]] && source "/home/josh/.sdkman/bin/sdkman-init.sh"
