#!/usr/bin/env bash

export SET_BOLD="\e[1m"
export SET_DIM="\e[2m"
export SET_UNDERLINED="\e[4m"
export SET_BLINK="\e[5m"
export SET_INVERTED="\e[7m"
export SET_HIDDEN="\e[8m"

export RESET_BOLD="\e[21m"
export RESET_DIM="\e[22m"
export RESET_UNDERLINED="\e[24m"
export RESET_BLINK="\e[25m"
export RESET_INVERTED="\e[27m"
export RESET_HIDDEN="\e[28m"

export FG_DEFAULT="\e[39m"
export FG_BLACK="\e[30m"
export FG_RED="\e[31m"
export FG_GREEN="\e[32m"
export FG_YELLOW="\e[33m"
export FG_BLUE="\e[34m"
export FG_MAGENTA="\e[35m"
export FG_CYAN="\e[36m"
export FG_GRAY_LIGHT="\e[37m"
export FG_GRAY_DARK="\e[90m"
export FG_RED_LIGHT="\e[91m"
export FG_GREEN_LIGHT="\e[92m"
export FG_YELLOW_LIGHT="\e[93m"
export FG_BLUE_LIGHT="\e[94m"
export FG_MAGENTA_LIGHT="\e[95m"
export FG_CYAN_LIGHT="\e[96m"
export FG_WHITE="\e[97m"

export BG_DEFAULT="\e[49m"
export BG_BLACK="\e[40m"
export BG_RED="\e[41m"
export BG_GREEN="\e[42m"
export BG_YELLOW="\e[43m"
export BG_BLUE="\e[44m"
export BG_MAGENTA="\e[45m"
export BG_CYAN="\e[46m"
export BG_GRAY_LIGHT="\e[47m"
export BG_GRAY_DARK="\e[100m"
export BG_RED_LIGHT="\e[101m"
export BG_GREEN_LIGHT="\e[102m"
export BG_YELLOW_LIGHT="\e[103m"
export BG_BLUE_LIGHT="\e[104m"
export BG_MAGENTA_LIGHT="\e[105m"
export BG_CYAN_LIGHT="\e[106m"
export BG_WHITE="\e[107m"

export RESET="\e[0m"

function echo_color {
  echo -en "$*"
}
