---
- hosts: localhost
  vars:
    - user:
        name: "josh"
    - build:
        pkgs:
          - git
          - vim
          - curl
          - wget
          - build-essential
          - cmake
          - python-dev
          - tmux
          - vagrant
          - python-pip # needed for the ansible pip module
          - bzip2 # needed for cmake
          - xsel # for clipboard operations in neovim
          - unzip # needed for neovim (or actually luarocks)
        brews:
          - ncurses
          - liquidprompt
          - tmux
          - autojump
          - ag
          - git-flow
          - bash-completion
        pips:
          - setuptools # needed for cmake, might actually be included with python-pip.. dunno
          - neovim # for vim/python plugins in neovim
        repos: 
        - repo: https://github.com/VundleVim/Vundle.vim 
          dest: /home/{{user.name}}/.vim/bundle/Vundle.vim 
        - repo: https://github.com/chriskempson/base16-shell  
          dest: /home/{{user.name}}/.config/base16-shell
        - repo: https://github.com/Homebrew/linuxbrew.git  
          dest: /home/{{user.name}}/.linuxbrew

  remote_user: "{{user.name}}"
  roles: 
    - basic-dev
    - role: ansible-nvm
      nvm: 
        user: "{{ user.name }}"
        become: yes
        version: master
        node_version: 0.12.7
    - role: rvm1-ansible
      sudo: true
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_install_path: '/home/{{ user.name }}/.rvm'
      rvm1_user: '{{ user.name }}'
