(deftheme josh-theme
  "Created 2021-07-07.")

(defface markup-gen-titles '((t (:weight bold))) "Used as the base face for titles in markup/adoc")

(custom-theme-set-faces
  'josh-theme
  '(default ((t (:family "Source Code Pro" :foundry "ADBO" :width normal :height 105 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#f8f8f2" :background "#282a36" :stipple nil :inherit nil))))
  '(cursor ((t (:background "#bd93f9"))))
  '(fixed-pitch ((t (:width normal :height 105 :weight normal :slant normal))))
  '(variable-pitch ((t (:family "Source Sans Pro" :foundry "ADBO" :width normal :height 105 :weight light :slant normal))))
  '(escape-glyph ((t (:foreground "#8be9fd"))))
  '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
  '(minibuffer-prompt ((t (:foreground "#bd93f9"))))
  '(highlight ((t (:foreground "#1E2029" :background "#bd93f9"))))
  '(region ((t (:extend t :background "#44475a"))))
  '(shadow ((t (:foreground "#6272a4"))))
  '(secondary-selection ((t (:extend t :background "#565761"))))
  '(trailing-whitespace ((t (:background "#ff5555"))))
  '(font-lock-builtin-face ((t (:foreground "#ffb86c"))))
  '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
  '(font-lock-comment-face ((t (:foreground "#6272a4"))))
  '(font-lock-constant-face ((t (:foreground "#8be9fd"))))
  '(font-lock-doc-face ((t (:foreground "#8995ba" :inherit (font-lock-comment-face)))))
  '(font-lock-function-name-face ((t (:foreground "#50fa7b"))))
  '(font-lock-keyword-face ((t (:foreground "#ff79c6"))))
  '(font-lock-negation-char-face ((t (:foreground "#bd93f9" :inherit (bold)))))
  '(font-lock-preprocessor-face ((t (:foreground "#bd93f9" :inherit (bold)))))
  '(font-lock-regexp-grouping-backslash ((t (:foreground "#bd93f9" :inherit (bold)))))
  '(font-lock-regexp-grouping-construct ((t (:foreground "#bd93f9" :inherit (bold)))))
  '(font-lock-string-face ((t (:foreground "#f1fa8c"))))
  '(font-lock-type-face ((t (:foreground "#bd93f9"))))
  '(font-lock-variable-name-face ((t (:foreground "#ffc9e8"))))
  '(font-lock-warning-face ((t (:inherit (warning)))))
  '(button ((t (:inherit (link)))))
  '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#bd93f9"))))
  '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
  '(fringe ((t (:foreground "#282a36" :background "#282a36" :inherit (default)))))
  '(header-line ((t (:foreground "#f8f8f2" :background "#282a36"))))
  '(tooltip ((t (:foreground "#f8f8f2" :background "#1E2029"))))
  '(mode-line ((t (:box nil :background "#22232d"))))
  '(mode-line-buffer-id ((t (:weight bold))))
  '(mode-line-emphasis ((t (:foreground "#bd93f9"))))
  '(mode-line-highlight ((t (:inherit (highlight)))))
  '(mode-line-inactive ((t (:box nil :foreground "#6272a4" :background "#252631"))))
  '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
  '(isearch-fail ((t (:weight bold :foreground "#1E2029" :background "#ff5555"))))
  '(lazy-highlight ((t (:weight bold :foreground "#f8f8f2" :background "#8466ae"))))
  '(match ((t (:weight bold :foreground "#50fa7b" :background "#1E2029"))))
  '(next-error ((t (:inherit (region)))))
  '(query-replace ((t (:inherit (isearch)))))
  '(markup-gen-face ((t (:foreground "#eeeeee"))))
  '(markup-gen-titles ((t (:weight bold))))
  '(markup-title-0-face ((t (:inherit markup-gen-titles :height 2.8))))
  '(markup-title-1-face ((t (:inherit markup-gen-titles :height 2.2))))
  '(markup-title-2-face ((t (:inherit markup-gen-titles :height 1.6))))
  '(markup-title-3-face ((t (:inherit markup-gen-titles :height 1.6 :weight normal))))
  '(markup-title-4-face ((t (:inherit markup-gen-titles :height 1.0 ))))
  '(markup-verbatim-face ((t (:foreground "#cdbade" ))))
  '(markup-typewriter-face ((t (:background "#523849" ))))
  '(markup-code-face ((t (:foreground "#cdbade" ))))


  )

(provide-theme 'josh-theme)
